# Generated by Django 6.0.2 on 2026-03-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='image',
            field=models.BooleanField(default=True),
        ),
    ]
