# Generated by Django 6.0.2 on 2026-03-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_userpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='uploaded_time',
            field=models.DateTimeField(),
        ),
    ]
