# Generated by Django 6.0.2 on 2026-03-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_userpost_uploaded_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='uploaded_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
